# Form implementation generated from reading ui file '/Users/quangvinh/Documents/Pythonfile/bonus_ex/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 245)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 111, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 40, 271, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonSaveChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSaveChart.setGeometry(QtCore.QRect(250, 90, 161, 51))
        self.pushButtonSaveChart.setObjectName("pushButtonSaveChart")
        self.pushButtonLoadFile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLoadFile.setGeometry(QtCore.QRect(410, 40, 91, 41))
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nguyen Quang Vinh - K234111460"))
        self.label.setText(_translate("MainWindow", "Choose dataset:"))
        self.pushButton.setText(_translate("MainWindow", "Open Chart in HTML"))
        self.pushButtonSaveChart.setText(_translate("MainWindow", "Save Chart to HTML"))
        self.pushButtonLoadFile.setText(_translate("MainWindow", "..."))
